route:
    receiver: 'slack'

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            username: 'nanjishidu'
            channel: '#test'
            api_url: 'https://hooks.slack.com/services/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'